name: Demo WorkFlow
"on": push
jobs:
  megastar:
    name: "MEGA JOB"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print Runner Host name
        run: hostname
        shell: bash
      - name: Print Runner IP Address
        run: curl -sL https://ipconfig.io
        shell: bash