name: Demo WorkFlow
"on": push
jobs:
  megastar:
    name: "MEGA JOB"
    runs-on: ubuntu-latest
    steps:
      - name: Print Runner Host name
        run: hostname
      - name: Print Runner IP Address
        run: curl https://ipconfig.io