# This is a demo workflow file to test github actions.
name: Demo WorkFlow
on:
  push:
   branches: [master, mega]
  pull_request:
    types: [closed]
    branches: [master, mega]
  schedule:
    - cron: "* * * * *"
jobs:
  megastar:
    name: "MEGA JOB"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print Runner Host name
        run: hostname
        shell: bash
      - name: Print Runner IP Address
        run: curl -sL https://ipconfig.io
        shell: bash
