# This is a demo workflow file to test github actions.
name: Demo WorkFlow
on:
  push:
    branches: [master, mega]
  pull_request:
    types: [closed]
    branches: [master, mega]
  schedule:
    - cron: "* * * * *"

jobs:
  megastar:
    name: "MEGA JOB"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print Runner Host name
        run: hostname
        shell: bash
      - name: Print Runner IP Address
        run: curl -sL https://ipconfig.io
        shell: bash
      - name: Setup Terraform wiht specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

superstar:
  name: "SUPER JOB"
  needs: megastar
  runs-on: ubuntu-latest
  defaults:
    run:
      shell: bash
  steps:
    - name: Print Runner Hostname
      run: hostname
      shell: bash
    - name: Print Runner IP Address
      run: curl -sL https://ipconfig.io
      shell: bash

powerstar:
  name: "POWER JOB"
  needs: superstar
  runs-on: ubuntu-latest
  defaults:
    run:
      shell: bash
  steps:
    - name: Print Runner Hostname
      run: hostname
      shell: bash
    - name: Print Runner IP Address
      run: curl -sL https://ipconfig.io
      shell: bash

rebelstar:
  name: "REBEL JOB"
  needs: powerstar
  runs-on: ubuntu-latest
  defaults:
    run:
      shell: bash
  steps:
    - name: Print Runner Hostname
      run: hostname
      shell: bash
    - name: Print Runner IP Address
      run: curl -sL https://ipconfig.io
      shell: bash


