# This is a demo workflow file to test github actions hiii.
name: YoungTiger WorkFlow
on:
 workflow_dispatch:
    inputs:
      TERRAFORM_DESTROY:
        description: 'Shall We Run Terraform Destroy?'     
        required: true
        default: 'DONT_DESTROY'
        type: choice
        options:
        - DONT_DESTROY
        - DESTROY
      ENVIRONMENT:
        description: 'Select Which Subscription You Want To Deploy?'
        required: true
        default: 'Development'
        type: choice
        options:
        - Production
        - Azure subscription 1



env:
  #TERRAFORM_DESTROY: "YES"
  ENVIRONMENT: "Production"
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ACTIONS_STEP_DEBUG: true


jobs:
  megastar:
    if: ${{ github.event.inputs.ENVIRONMENT == 'Production' }}
    name: "MEGA JOB"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print Runner Host name
        run: hostname
        shell: bash
      - name: Print Runner IP Address
        run: curl -sL https://ipconfig.io
        shell: bash
      - name: Setup Terraform wiht specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"
    
  superstar:
    if: ${{ github.event.inputs.ENVIRONMENT == 'Azure subscription 1' }}
    name: "SUPER JOB"
    needs: megastar
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print Runner Host name
        run: hostname
        shell: bash
      - name: Print Runner IP Address
        run: curl -sL https://ipconfig.io
        shell: bash
  
  # powerstar:
  #   name: "POWER JOB"
  #   needs: superstar
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - name: Print Runner Host name
  #       run: hostname
  #       shell: bash
  #     - name: Print Runner IP Address
  #       run: curl -sL https://ipconfig.io
  #       shell: bash
  
  # rebelstar:
  #   name: "POWER JOB"
  #   needs: powerstar
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - name: Print Runner Host name
  #       run: hostname
  #       shell: bash
  #     - name: Print Runner IP Address
  #       run: curl -sL https://ipconfig.io
  #       shell: bash
      






